import type { AdminAgencyAccess } from "@/lib/agencies/admin-access-core";

export type LegalSnapshot = Readonly<{ legalName: string; taxId: string | null; legalAddress: string | null; supportEmail: string | null; supportPhone: string | null; jurisdiction: string | null }>;
export type ContentSnapshot = Readonly<{ templateVersion: number; title: string; introductoryText: string | null; termsText: string; paymentPolicyText: string | null; cancellationPolicyText: string | null; travelerResponsibilityText: string | null; jurisdictionText: string | null; effectiveFrom: string | null }>;
export type CurrentContract = Readonly<{ status: "prepared" | "accepted"; templateVersion: number; preparedAt: string }>;
export type ContractTemplateSource = Readonly<{ id: string; version: number; status: string; title: string; introductoryText: string | null; termsText: string; paymentPolicyText: string | null; cancellationPolicyText: string | null; travelerResponsibilityText: string | null; jurisdictionText: string | null; effectiveFrom: string | null }>;
export interface ReservationContractRepository { findReservation(input: { agencyId: string; reservationId: string }): Promise<boolean>; findCurrent(input: { agencyId: string; reservationId: string }): Promise<CurrentContract | null>; findLegalProfile(input: { agencyId: string }): Promise<LegalSnapshot | null>; findActiveTemplate(input: { agencyId: string }): Promise<ContractTemplateSource | null>; insert(input: { agencyId: string; reservationId: string; template: ContractTemplateSource; legal: LegalSnapshot; actorId: string }): Promise<CurrentContract>; }
export type PrepareReservationContractResult = Readonly<{ status: "prepared" | "existing"; contract: CurrentContract }> | Readonly<{ status: "unauthenticated" | "selection_required" | "forbidden" | "not_found" | "legal_profile_required" | "active_template_required" | "invalid_structure" }>;
export class ReservationContractError extends Error { readonly name = "ReservationContractError"; constructor() { super("No fue posible preparar el contrato."); } }
const uuid = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
function blocked(access: AdminAgencyAccess): Exclude<PrepareReservationContractResult, Readonly<{ status: "prepared" | "existing"; contract: CurrentContract }> | Readonly<{ status: "not_found" }> | Readonly<{ status: "legal_profile_required" }> | Readonly<{ status: "active_template_required" }> | Readonly<{ status: "invalid_structure" }>> | null { if (access.status === "unauthenticated") return { status: "unauthenticated" }; if (access.status === "selection_required") return { status: "selection_required" }; if (access.status === "forbidden") return { status: "forbidden" }; return null; }
export function createReservationContractService(deps: { resolveAccess: (input: { requestedAgencySlug?: string }) => Promise<AdminAgencyAccess>; repository: ReservationContractRepository | (() => ReservationContractRepository) }) { const repo = () => typeof deps.repository === "function" ? deps.repository() : deps.repository; return { async prepare(input: { requestedAgencySlug: unknown; reservationId: unknown }): Promise<PrepareReservationContractResult> { let access: AdminAgencyAccess; try { access = await deps.resolveAccess({ requestedAgencySlug: typeof input.requestedAgencySlug === "string" ? input.requestedAgencySlug : undefined }); } catch { throw new ReservationContractError(); } const denied = blocked(access); if (denied) return denied; if (access.status !== "authorized") return { status: "forbidden" }; if (!uuid(input.reservationId)) return { status: "not_found" }; try { const data = repo(), scope = { agencyId: access.agency.agencyId, reservationId: input.reservationId }; if (!await data.findReservation(scope)) return { status: "not_found" }; const existing = await data.findCurrent(scope); if (existing) return { status: "existing", contract: existing }; const legal = await data.findLegalProfile({ agencyId: scope.agencyId }); if (!legal || !legal.legalName.trim()) return { status: "legal_profile_required" }; const template = await data.findActiveTemplate({ agencyId: scope.agencyId }); if (!template) return { status: "active_template_required" }; if (template.status !== "active" || template.version < 1 || !template.title.trim() || !template.termsText.trim()) return { status: "invalid_structure" }; try { return { status: "prepared", contract: await data.insert({ ...scope, template, legal, actorId: access.identity.userId }) }; } catch (error) { const retry = await data.findCurrent(scope); if (retry) return { status: "existing", contract: retry }; throw error; } } catch (error) { if (error instanceof ReservationContractError) throw error; throw new ReservationContractError(); } } }; }
